# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Build and deploy a release

on:
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        default: false

jobs:
  lint_check:
    name: Build
    uses: ./.github/workflows/_lint.yaml

  build_doc:
    name: Build
    needs: lint_check
    uses: ./.github/workflows/_build_doc.yaml

  build_wheel:
    name: Build
    needs: lint_check
    uses: ./.github/workflows/_build_wheel.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cpu', 'cu117', 'cu118'],
          sanitizer: ['nosan'],
          include: [
            {
              py: '3.8',
              build_variant: 'cpu',
              sanitizer: 'asan_ubsan'
            }
          ]
        }

  build_conda:
    name: Build
    needs: lint_check
    uses: ./.github/workflows/_build_conda.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cpu', 'cu117', 'cu118'],
          sanitizer: ['nosan'],
          include: [
            {
              py: '3.8',
              build_variant: 'cpu',
              sanitizer: 'asan_ubsan'
            }
          ]
        }

  test_wheel_cpu:
    name: Test (CPU)
    needs: build_wheel
    uses: ./.github/workflows/_test_wheel.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cpu'],
          sanitizer: ['nosan'],
          include: [
            {
              py: '3.8',
              build_variant: 'cpu',
              sanitizer: 'asan_ubsan'
            }
          ]
        }

  test_wheel_cu117:
    name: Test (CUDA 11.7)
    needs: test_wheel_cpu
    uses: ./.github/workflows/_test_wheel.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cu117'],
          sanitizer: ['nosan']
        }

  test_wheel_cu118:
    name: Test (CUDA 11.8)
    needs: test_wheel_cu117
    uses: ./.github/workflows/_test_wheel.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cu118'],
          sanitizer: ['nosan']
        }

  test_conda_cpu:
    name: Test (CPU)
    needs: build_conda
    uses: ./.github/workflows/_test_conda.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cpu'],
          sanitizer: ['nosan'],
          include: [
            {
              py: '3.8',
              build_variant: 'cpu',
              sanitizer: 'asan_ubsan'
            }
          ]
        }

  test_conda_cu117:
    name: Test (CUDA 11.7)
    needs: test_conda_cpu
    uses: ./.github/workflows/_test_conda.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cu117'],
          sanitizer: ['nosan']
        }

  test_conda_cu118:
    name: Test (CUDA 11.8)
    needs: test_conda_cu117
    uses: ./.github/workflows/_test_conda.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cu118'],
          sanitizer: ['nosan']
        }

  deploy:
    name: Deploy
    if: github.event.inputs.deploy == 'true'
    needs: [build_doc, test_wheel_cu118, test_conda_cu118]
    uses: ./.github/workflows/_deploy.yaml
    with:
      matrix: |
        {
          py: ['3.8', '3.9', '3.10'],
          build_variant: ['cpu', 'cu117', 'cu118'],
        }
      s3_wheel_path: pytorch/whl
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
      aws_key_id: ${{ secrets.AWS_PYTORCH_KEY_ID }}
      aws_access_key: ${{ secrets.AWS_PYTORCH_ACCESS_KEY }}
