################################################################################
#
# Copyright 2023 ByteDance Ltd. and/or its affiliates. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkpoint/utilities/server/mem_file_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n2checkpoint/utilities/server/mem_file_service.proto">\n\x1dVeScaleCheckpointWriteRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x08 \x01(\t" \n\x1eVeScaleCheckpointWriteResponse",\n\x1cVeScaleCheckpointReadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"0\n\x1dVeScaleCheckpointReadResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c"M\n\x1eVeScaleCheckpointRenameRequest\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x0b\n\x03\x64st\x18\x02 \x01(\t\x12\x11\n\toverwrite\x18\x03 \x01(\x08"!\n\x1fVeScaleCheckpointRenameResponse".\n\x1eVeScaleCheckpointRemoveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"!\n\x1fVeScaleCheckpointRemoveResponse"/\n\x1fVeScaleCheckpointListdirRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"1\n VeScaleCheckpointListdirResponse\x12\r\n\x05names\x18\x01 \x03(\t".\n\x1eVeScaleCheckpointExistsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"1\n\x1fVeScaleCheckpointExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\xf9\x03\n\x1fVeScaleCheckpointMemFileService\x12L\n\x05Write\x12\x1e.VeScaleCheckpointWriteRequest\x1a\x1f.VeScaleCheckpointWriteResponse"\x00(\x01\x12I\n\x04Read\x12\x1d.VeScaleCheckpointReadRequest\x1a\x1e.VeScaleCheckpointReadResponse"\x00\x30\x01\x12M\n\x06Rename\x12\x1f.VeScaleCheckpointRenameRequest\x1a .VeScaleCheckpointRenameResponse"\x00\x12M\n\x06Remove\x12\x1f.VeScaleCheckpointRemoveRequest\x1a .VeScaleCheckpointRemoveResponse"\x00\x12P\n\x07Listdir\x12 .VeScaleCheckpointListdirRequest\x1a!.VeScaleCheckpointListdirResponse"\x00\x12M\n\x06\x45xists\x12\x1f.VeScaleCheckpointExistsRequest\x1a .VeScaleCheckpointExistsResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "checkpoint.utilities.server.mem_file_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_VESCALECHECKPOINTWRITEREQUEST"]._serialized_start = 54
    _globals["_VESCALECHECKPOINTWRITEREQUEST"]._serialized_end = 116
    _globals["_VESCALECHECKPOINTWRITERESPONSE"]._serialized_start = 118
    _globals["_VESCALECHECKPOINTWRITERESPONSE"]._serialized_end = 150
    _globals["_VESCALECHECKPOINTREADREQUEST"]._serialized_start = 152
    _globals["_VESCALECHECKPOINTREADREQUEST"]._serialized_end = 196
    _globals["_VESCALECHECKPOINTREADRESPONSE"]._serialized_start = 198
    _globals["_VESCALECHECKPOINTREADRESPONSE"]._serialized_end = 246
    _globals["_VESCALECHECKPOINTRENAMEREQUEST"]._serialized_start = 248
    _globals["_VESCALECHECKPOINTRENAMEREQUEST"]._serialized_end = 325
    _globals["_VESCALECHECKPOINTRENAMERESPONSE"]._serialized_start = 327
    _globals["_VESCALECHECKPOINTRENAMERESPONSE"]._serialized_end = 360
    _globals["_VESCALECHECKPOINTREMOVEREQUEST"]._serialized_start = 362
    _globals["_VESCALECHECKPOINTREMOVEREQUEST"]._serialized_end = 408
    _globals["_VESCALECHECKPOINTREMOVERESPONSE"]._serialized_start = 410
    _globals["_VESCALECHECKPOINTREMOVERESPONSE"]._serialized_end = 443
    _globals["_VESCALECHECKPOINTLISTDIRREQUEST"]._serialized_start = 445
    _globals["_VESCALECHECKPOINTLISTDIRREQUEST"]._serialized_end = 492
    _globals["_VESCALECHECKPOINTLISTDIRRESPONSE"]._serialized_start = 494
    _globals["_VESCALECHECKPOINTLISTDIRRESPONSE"]._serialized_end = 543
    _globals["_VESCALECHECKPOINTEXISTSREQUEST"]._serialized_start = 545
    _globals["_VESCALECHECKPOINTEXISTSREQUEST"]._serialized_end = 591
    _globals["_VESCALECHECKPOINTEXISTSRESPONSE"]._serialized_start = 593
    _globals["_VESCALECHECKPOINTEXISTSRESPONSE"]._serialized_end = 642
    _globals["_VESCALECHECKPOINTMEMFILESERVICE"]._serialized_start = 645
    _globals["_VESCALECHECKPOINTMEMFILESERVICE"]._serialized_end = 1150
# @@protoc_insertion_point(module_scope)
