################################################################################
#
# Copyright 2023 ByteDance Ltd. and/or its affiliates. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import (
    report_service_pb2 as checkpoint_dot_utilities_dot_server_dot_report__service__pb2,
)


class VeScaleCheckpointReportServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Gather = channel.unary_unary(
            "/VeScaleCheckpointReportService/Gather",
            request_serializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGatherRequest.SerializeToString,
            response_deserializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGatherResponse.FromString,
        )
        self.Broadcast = channel.unary_unary(
            "/VeScaleCheckpointReportService/Broadcast",
            request_serializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointBroadcastRequest.SerializeToString,
            response_deserializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointBroadcastResponse.FromString,
        )
        self.GetStatus = channel.unary_unary(
            "/VeScaleCheckpointReportService/GetStatus",
            request_serializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGetStatusRequest.SerializeToString,
            response_deserializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGetStatusResponse.FromString,
        )


class VeScaleCheckpointReportServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Gather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VeScaleCheckpointReportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Gather": grpc.unary_unary_rpc_method_handler(
            servicer.Gather,
            request_deserializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGatherRequest.FromString,
            response_serializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGatherResponse.SerializeToString,
        ),
        "Broadcast": grpc.unary_unary_rpc_method_handler(
            servicer.Broadcast,
            request_deserializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointBroadcastRequest.FromString,
            response_serializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointBroadcastResponse.SerializeToString,
        ),
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGetStatusRequest.FromString,
            response_serializer=checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGetStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("VeScaleCheckpointReportService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class VeScaleCheckpointReportService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Gather(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/VeScaleCheckpointReportService/Gather",
            checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGatherRequest.SerializeToString,
            checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGatherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Broadcast(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/VeScaleCheckpointReportService/Broadcast",
            checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointBroadcastRequest.SerializeToString,
            checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointBroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/VeScaleCheckpointReportService/GetStatus",
            checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGetStatusRequest.SerializeToString,
            checkpoint_dot_utilities_dot_server_dot_report__service__pb2.VeScaleCheckpointGetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
