################################################################################
#
# Copyright 2023 ByteDance Ltd. and/or its affiliates. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: omnistore/utilities/server/mem_file_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n1OmniStore/utilities/server/mem_file_service.proto"6\n\x15OmniStoreWriteRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x08 \x01(\t"\x18\n\x16OmniStoreWriteResponse"$\n\x14OmniStoreReadRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"(\n\x15OmniStoreReadResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c"E\n\x16OmniStoreRenameRequest\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x0b\n\x03\x64st\x18\x02 \x01(\t\x12\x11\n\toverwrite\x18\x03 \x01(\x08"\x19\n\x17OmniStoreRenameResponse"&\n\x16OmniStoreRemoveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\x19\n\x17OmniStoreRemoveResponse"\'\n\x17OmniStoreListdirRequest\x12\x0c\n\x04name\x18\x01 \x01(\t")\n\x18OmniStoreListdirResponse\x12\r\n\x05names\x18\x01 \x03(\t"&\n\x16OmniStoreExistsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t")\n\x17OmniStoreExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\x91\x03\n\x17OmniStoreMemFileService\x12<\n\x05Write\x12\x16.OmniStoreWriteRequest\x1a\x17.OmniStoreWriteResponse"\x00(\x01\x12\x39\n\x04Read\x12\x15.OmniStoreReadRequest\x1a\x16.OmniStoreReadResponse"\x00\x30\x01\x12=\n\x06Rename\x12\x17.OmniStoreRenameRequest\x1a\x18.OmniStoreRenameResponse"\x00\x12=\n\x06Remove\x12\x17.OmniStoreRemoveRequest\x1a\x18.OmniStoreRemoveResponse"\x00\x12@\n\x07Listdir\x12\x18.OmniStoreListdirRequest\x1a\x19.OmniStoreListdirResponse"\x00\x12=\n\x06\x45xists\x12\x17.OmniStoreExistsRequest\x1a\x18.OmniStoreExistsResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "omnistore.utilities.server.mem_file_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_OMNISTOREWRITEREQUEST"]._serialized_start = 53
    _globals["_OMNISTOREWRITEREQUEST"]._serialized_end = 107
    _globals["_OMNISTOREWRITERESPONSE"]._serialized_start = 109
    _globals["_OMNISTOREWRITERESPONSE"]._serialized_end = 133
    _globals["_OMNISTOREREADREQUEST"]._serialized_start = 135
    _globals["_OMNISTOREREADREQUEST"]._serialized_end = 171
    _globals["_OMNISTOREREADRESPONSE"]._serialized_start = 173
    _globals["_OMNISTOREREADRESPONSE"]._serialized_end = 213
    _globals["_OMNISTORERENAMEREQUEST"]._serialized_start = 215
    _globals["_OMNISTORERENAMEREQUEST"]._serialized_end = 284
    _globals["_OMNISTORERENAMERESPONSE"]._serialized_start = 286
    _globals["_OMNISTORERENAMERESPONSE"]._serialized_end = 311
    _globals["_OMNISTOREREMOVEREQUEST"]._serialized_start = 313
    _globals["_OMNISTOREREMOVEREQUEST"]._serialized_end = 351
    _globals["_OMNISTOREREMOVERESPONSE"]._serialized_start = 353
    _globals["_OMNISTOREREMOVERESPONSE"]._serialized_end = 378
    _globals["_OMNISTORELISTDIRREQUEST"]._serialized_start = 380
    _globals["_OMNISTORELISTDIRREQUEST"]._serialized_end = 419
    _globals["_OMNISTORELISTDIRRESPONSE"]._serialized_start = 421
    _globals["_OMNISTORELISTDIRRESPONSE"]._serialized_end = 462
    _globals["_OMNISTOREEXISTSREQUEST"]._serialized_start = 464
    _globals["_OMNISTOREEXISTSREQUEST"]._serialized_end = 502
    _globals["_OMNISTOREEXISTSRESPONSE"]._serialized_start = 504
    _globals["_OMNISTOREEXISTSRESPONSE"]._serialized_end = 545
    _globals["_OMNISTOREMEMFILESERVICE"]._serialized_start = 548
    _globals["_OMNISTOREMEMFILESERVICE"]._serialized_end = 949
# @@protoc_insertion_point(module_scope)
