################################################################################
#
# Copyright 2023 ByteDance Ltd. and/or its affiliates. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: omnistore/utilities/server/report_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n/omnistore/utilities/server/report_service.proto"Y\n\x16OmniStoreGatherRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x13\n\x0bwith_result\x18\x04 \x01(\x08"+\n\x17OmniStoreGatherResponse\x12\x10\n\x08\x63ontents\x18\x01 \x03(\x0c"Y\n\x19OmniStoreBroadcastRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x10\n\x08src_rank\x18\x04 \x01(\x05"-\n\x1aOmniStoreBroadcastResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c"\x1b\n\x19OmniStoreGetStatusRequest",\n\x1aOmniStoreGetStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x0c\x32\xe7\x01\n\x16OmniStoreReportService\x12=\n\x06Gather\x12\x17.OmniStoreGatherRequest\x1a\x18.OmniStoreGatherResponse"\x00\x12\x46\n\tBroadcast\x12\x1a.OmniStoreBroadcastRequest\x1a\x1b.OmniStoreBroadcastResponse"\x00\x12\x46\n\tGetStatus\x12\x1a.OmniStoreGetStatusRequest\x1a\x1b.OmniStoreGetStatusResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "omnistore.utilities.server.report_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_OMNISTOREGATHERREQUEST"]._serialized_start = 51
    _globals["_OMNISTOREGATHERREQUEST"]._serialized_end = 140
    _globals["_OMNISTOREGATHERRESPONSE"]._serialized_start = 142
    _globals["_OMNISTOREGATHERRESPONSE"]._serialized_end = 185
    _globals["_OMNISTOREBROADCASTREQUEST"]._serialized_start = 187
    _globals["_OMNISTOREBROADCASTREQUEST"]._serialized_end = 276
    _globals["_OMNISTOREBROADCASTRESPONSE"]._serialized_start = 278
    _globals["_OMNISTOREBROADCASTRESPONSE"]._serialized_end = 323
    _globals["_OMNISTOREGETSTATUSREQUEST"]._serialized_start = 325
    _globals["_OMNISTOREGETSTATUSREQUEST"]._serialized_end = 352
    _globals["_OMNISTOREGETSTATUSRESPONSE"]._serialized_start = 354
    _globals["_OMNISTOREGETSTATUSRESPONSE"]._serialized_end = 398
    _globals["_OMNISTOREREPORTSERVICE"]._serialized_start = 401
    _globals["_OMNISTOREREPORTSERVICE"]._serialized_end = 632
# @@protoc_insertion_point(module_scope)
