################################################################################
#
# Copyright 2023 ByteDance Ltd. and/or its affiliates. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkpoint/utilities/server/report_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n0checkpoint/utilities/server/report_service.proto"a\n\x1eVeScaleCheckpointGatherRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x13\n\x0bwith_result\x18\x04 \x01(\x08"3\n\x1fVeScaleCheckpointGatherResponse\x12\x10\n\x08\x63ontents\x18\x01 \x03(\x0c"a\n!VeScaleCheckpointBroadcastRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x10\n\x08src_rank\x18\x04 \x01(\x05"5\n"VeScaleCheckpointBroadcastResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c"#\n!VeScaleCheckpointGetStatusRequest"4\n"VeScaleCheckpointGetStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x0c\x32\x9f\x02\n\x1eVeScaleCheckpointReportService\x12M\n\x06Gather\x12\x1f.VeScaleCheckpointGatherRequest\x1a .VeScaleCheckpointGatherResponse"\x00\x12V\n\tBroadcast\x12".VeScaleCheckpointBroadcastRequest\x1a#.VeScaleCheckpointBroadcastResponse"\x00\x12V\n\tGetStatus\x12".VeScaleCheckpointGetStatusRequest\x1a#.VeScaleCheckpointGetStatusResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "checkpoint.utilities.server.report_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_VESCALECHECKPOINTGATHERREQUEST"]._serialized_start = 52
    _globals["_VESCALECHECKPOINTGATHERREQUEST"]._serialized_end = 149
    _globals["_VESCALECHECKPOINTGATHERRESPONSE"]._serialized_start = 151
    _globals["_VESCALECHECKPOINTGATHERRESPONSE"]._serialized_end = 202
    _globals["_VESCALECHECKPOINTBROADCASTREQUEST"]._serialized_start = 204
    _globals["_VESCALECHECKPOINTBROADCASTREQUEST"]._serialized_end = 301
    _globals["_VESCALECHECKPOINTBROADCASTRESPONSE"]._serialized_start = 303
    _globals["_VESCALECHECKPOINTBROADCASTRESPONSE"]._serialized_end = 356
    _globals["_VESCALECHECKPOINTGETSTATUSREQUEST"]._serialized_start = 358
    _globals["_VESCALECHECKPOINTGETSTATUSREQUEST"]._serialized_end = 393
    _globals["_VESCALECHECKPOINTGETSTATUSRESPONSE"]._serialized_start = 395
    _globals["_VESCALECHECKPOINTGETSTATUSRESPONSE"]._serialized_end = 447
    _globals["_VESCALECHECKPOINTREPORTSERVICE"]._serialized_start = 450
    _globals["_VESCALECHECKPOINTREPORTSERVICE"]._serialized_end = 737
# @@protoc_insertion_point(module_scope)
